var Demos = [
    { url : "QuadTreeDemo/quadtreedemo.html",
      title : "QuadTree",
      img: "",
      caption : "In a dot eat dot world",
    },
    { url : "BresenhamDemo/bresenhamdemo.html",
      title : "Bresenham",
      img: "",
      caption : "The Line Algorithm",
    },
    { url : "RayCast/RayCast.html",
      title : "Ray Casting",
      img: "",
      caption : "Mapping 2D to 3D",
    },
    { url : "DestructibleTerrainDemo/destructibleterrain.html",
      title : "Destructible Terrain",
      img: "",
      caption : "Via QuadTree Rendering",
    },
];

var Projects = [
    {
      url : "http://prajogotio.github.io/parquer/parquer.html",
      title : 'parquer',
      img : 'img/parquer.jpg',
      caption : "A Neo-classical space shooting game, featuring a 2D inertial physics engine and a 360 shooting experience. In this game, space dots are your enemies, and be sure to kill them all. Be sure in the lookout for parquers, which grants unforeseen powers to its beholder!"
    },
    { url : "fross_game/fross.html",
      title: "Fross",
      img: "img/fross.jpg",
      caption: "A game inspired by a concept in graph theory. The player is to step on every tile on the maze without stepping on the same tile twice (yeah ideally) to open the door the next level.. Be careful, can be quite addictive! <br>Trapped in Hamiltonian World...",
    },
    { url : "boom/boom.html",
      title : "Boom",
      img: "img/boom.jpg",
      caption : "A First person shooting game which is written on vanilla javascript, using a technique called raycasting. It was quite a fun experience to create the maze, and an amazing one as well, because you can really see how a 2D array of 0s and 1s is being rendered as a nearly 3D maze. Anyway, in this game, you are supposed to find a way out of Boom, and may the odds be ever in your favour!",
    },
    { url : "trailee/trailee.html",
      title : "Trailee",
      img: "img/trailee.jpg",
      caption : "In this project, I wanted to demonstrate the hidden power of linear data structure such as linked list, which can behave in a non-linear and very natural way such as this moving linked list. It follows the mouse pointer to form a worm-like structure. It's pretty satisfying to watch!",
    },
    { url : "deterra/deterra.html",
      title : "Deterra",
      img: "img/deterra.png",
      caption : "This games features a destructible terrain based on an implementation of quadtree. The player is to find a way to survive as long as possible on the platform, which is constantly bombarded by a battalion of bombers from the sky.",
    },
    { url : "Space/Space.html",
      title : "Space Game",
      img: "img/space.jpg",
      caption : "The first game that I've ever created. It features a spaceship which is equipped with a powerful but heavy weaponary. Enemies will keep on appearing until they find a way to destroy you.",
    },
];
