var Demos = [
    {
      url : "http://prajogotio.github.io/perceptron",
      title : "Perceptron Live Demo",
      img : "img/perceptron.jpg",
      caption : "A live demo of one of the simplest machine learning algorithm called perceptron, which attempts to classify a set of data into two binary classifications. In this demo you can change the iteration limit for the perceptron algorithm and freely add new data points to the learning space."
    },
    { url : "QuadTreeDemo/quadtreedemo.html",
      title : "QuadTree",
      img: "img/quadtree.jpg",
      caption : "In a dot eat dot world",
    },
    {
      url : "http://prajogotio.github.io/recursive_bubble/out/RecursiveBubble.jar",
      title : "Recursive Bubble",
      img : "img/recursive-bubble.png",
      caption : "Applying design patterns on a recursive structure."
    },
    {
      url : "simpleMesh/simpleMesh.html",
      title : "3D Projection Demo",
      img : "img/simple3d.png",
      caption : "Simple Rotational 3D Cube Projection Demo",
    },
    { url : "BresenhamDemo/bresenhamdemo.html",
      title : "Bresenham",
      img: "img/bresenham.png",
      caption : "The Line Algorithm",
    },
    { url : "RayCast/RayCast.html",
      title : "Ray Casting",
      img: "img/raycasting.png",
      caption : "Mapping 2D to 3D",
    },
    { url : "DestructibleTerrainDemo/destructibleterrain.html",
      title : "Destructible Terrain",
      img: "img/destructible-terrain.png",
      caption : "Via QuadTree Rendering",
    },
];

var Projects = [
    {
      url : "http://piggi.herokuapp.com/",
      title : "piggi.io",
      img : "img/piggi.png",
      caption: "My second experience writing a multiplayer game. piggi is a real-time strategy game which features a tower-defense style gameplay. This game was written out of my motivation to implement a synchronised command-log architecture. The game is live at piggi.herokuapp.com"
    },
    {
      url : "http://nextep.herokuapp.com/",
      title : "Nextep",
      img : "img/nextep.png",
      caption: "My first attempt on distributed client-server multiplayer game development. The motivation was to discover how Gunbound and Worms' destructible terrain system works. During the development of the distributed computation, I learnt many valuable lessons on event-driven socket programming, event-relaying system, sychronisation issues, and latency problems. The game is currently running at nextep.herokuapp.com."
    },
    {
      url : "http://prajogotio.github.io/crosspath",
      title : "CrossPath",
      img : "img/crosspath.png",
      caption: "A 2D Platformer RPG/RTS which makes use of trailing Camera. This side-project was intended to break the monotony of school life. The gameplay is simple yet rich and challenging.",
    },
    {
      url : "http://prajogotio.github.io/EasieR",
      title : "EasieR",
      img : "img/easier.png",
      caption : "EasieR is an ER Diagram drawing tool which features convenience and intuitive interface. The motivation behind this app is simply because there are not many good tools (at least that I know of) that can quickly allow students who are studying database concepts to draw an ER diagram quickly and efficiently. This is my first time for writing an elaborate productivity tool, and this has been an enriching experience",
    },
    {
      url : "http://prajogotio.github.io/fbperspective",
      title : "Perspective",
      img : "img/perspective.jpg",
      caption: "An app that my friend and I developed during 2015 Facebook Singapore Hackathon, for which we won the 2nd place overall. The app features interesting and beautiful uses of Google Photosphere. Apparently the judges were impressed with the UI design :). The app is best viewed using Google Chrome on a normal sized notebook.",
    },
    {
      url : "http://prajogotio.github.io/limelight/out/Limelight.jar",
      img : "img/limelight.jpg",
      title : "Limelight",
      caption: "A remake of childhood memories. Limelight is written on Java and makes interesting use of JavaFX Canvas 2D and Timeline.",
    },
    {
      url : "http://prajogotio.github.io/Spardiac/Spardiac.html",
      title : 'Spardiac',
      img : 'img/spardiac.jpg',
      caption : 'I have just *accidentally* created my own 3D rendering engine on Javascript, which features wireframe-like 3D rendering system purely using linear algebra, perspective projections, and insights on 3D calculations. The renderer can practically render any type of 3D polygons defined using points and segments of lines, providing a lot of room for extensibility and usability. Here I put a demo on the engine, which I themed "How does it feel to be an Ironman?". It was a tedious job, but was fun and fulfilling!'
    },
    {
      url : "http://prajogotio.github.io/parquer/parquer.html",
      title : 'parquer',
      img : 'img/parquer.jpg',
      caption : "A Neo-classical space shooting game, featuring a 2D inertial physics engine and a 360 shooting experience. In this game, space dots are your enemies, and be sure to kill them all. Be sure in the lookout for parquers, which grants unforeseen powers to its beholder!"
    },
    { url : "fross_game/fross.html",
      title: "Fross",
      img: "img/fross.jpg",
      caption: "A game inspired by a concept in graph theory. The player is to step on every tile on the maze without stepping on the same tile twice (yeah ideally) to open the door the next level.. Be careful, can be quite addictive! <br>Trapped in Hamiltonian World...",
    },
    { url : "boom/boom.html",
      title : "Boom",
      img: "img/boom.jpg",
      caption : "A First person shooting game which is written on vanilla javascript, using a technique called raycasting. It was quite a fun experience to create the maze, and an amazing one as well, because you can really see how a 2D array of 0s and 1s is being rendered as a nearly 3D maze. Anyway, in this game, you are supposed to find a way out of Boom, and may the odds be ever in your favour!",
    },
    {
      title : "pervPong",
      url : "http://prajogotio.github.io/pervPong/jar/pervPong.jar",
      img : "img/pervpong.jpg",
      caption : "My simple take on the classical Pong game, written on Java. This motivation was mostly to practice on implementing several object oriented design principles and design patterns in general.",
    },
    { url : "trailee/trailee.html",
      title : "Trailee",
      img: "img/trailee.jpg",
      caption : "In this project, I wanted to demonstrate the hidden power of linear data structure such as linked list, which can behave in a non-linear and very natural way such as this moving linked list. It follows the mouse pointer to form a worm-like structure. It's pretty satisfying to watch!",
    },
    { url : "deterra/deterra.html",
      title : "Deterra",
      img: "img/deterra.png",
      caption : "This games features a destructible terrain based on an implementation of quadtree. The player is to find a way to survive as long as possible on the platform, which is constantly bombarded by a battalion of bombers from the sky.",
    },
    { url : "Space/Space.html",
      title : "Space Game",
      img: "img/space.jpg",
      caption : "The first game that I've ever created. It features a spaceship which is equipped with a powerful but heavy weaponary. Enemies will keep on appearing until they find a way to destroy you.",
    },
];
