var DataStructures = [
    { url : "QuadTreeDemo/quadtreedemo.html",
      title : "QuadTree",
      caption : "In a dot eat dot world",
    },
    { url : "BresenhamDemo/bresenhamdemo.html",
      title : "Bresenham",
      caption : "The Line Algorithm",
    },
    { url : "RayCast/RayCast.html",
      title : "Ray Casting",
      caption : "Mapping 2D to 3D",
    },
    { url : "DestructibleTerrainDemo/destructibleterrain.html",
      title : "Destructible Terrain",
      caption : "Via QuadTree Rendering",
    },
];

var Projects = [
    { url : "fross_game/fross.html",
      title: "Fross",
      caption: "Trapped in Hamiltonian World"
    },
    { url : "deterra/deterra.html",
      title : "Deterra",
      caption : "Destructible Quadtree Game",
    },
    { url : "Space/Space.html",
      title : "Space Game",
      caption : "Experimental Project",
    },
    { url : "boom/boom.html",
      title : "Boom",
      caption : "FPS By RayCasting 2.5D Game",
    },
    { url : "trailee/trailee.html",
      title : "Trailee",
      caption : "linked list that's alive",
    },
];
